// Render the inline API documentation to docs/api.md (`pnpm gen:api`), for reading on GitHub. The CLI
// (`pricesim api`, `pricesim describe`) reads the same registry; test/docs.test.ts checks the file is current.
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import '../src/index.ts'
import '../src/catalog/aws/index.ts'
import { allDocs, renderDoc, type ApiDoc } from '../src/docs/registry.ts'

const ORDER = ['pricesim', 'pricesim/model', 'pricesim/aws', 'pricesim/docs']

export const renderApiMarkdown = (): string => {
  const byModule = new Map<string, ApiDoc[]>()
  for (const d of allDocs().filter((x) => !x.internal)) byModule.set(d.module, [...(byModule.get(d.module) ?? []), d])
  const mods = [...byModule.keys()].sort(
    (a, b) => (ORDER.indexOf(a) + 1 || 99) - (ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b),
  )
  const anchor = (m: string) => m.replace(/[^a-z0-9]+/g, '-')
  const out = [
    '# API reference',
    '',
    '<!-- Generated by `pnpm gen:api` from the inline docs (`doc({ … })` next to each export). Do not edit. -->',
    '',
    'The same content is available from the CLI: `pricesim api` lists it, `pricesim describe <name>` shows one entry. Internal exports are left out (`pricesim api --all` lists them).',
    '',
    ...mods.map((m) => `- [\`${m}\`](#${anchor(m)})`),
  ]
  for (const m of mods) {
    out.push('', `## ${m}`, '', `<a id="${anchor(m)}"></a>`)
    for (const d of byModule.get(m)!)
      out.push('', renderDoc(d).replace(/^# /, '### ').replace(/^## /gm, '#### ').trimEnd())
  }
  return out.join('\n') + '\n'
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(fileURLToPath(new URL('../docs/api.md', import.meta.url)), renderApiMarkdown())
  process.stdout.write('wrote docs/api.md\n')
}
