// Generates src/core/dim-tables.gen.ts: exponent add/negate lookup tables for type-level dimensional analysis.
import { writeFileSync } from 'node:fs'

const MAX = 4
const exps = Array.from({ length: 2 * MAX + 1 }, (_, i) => i - MAX)
const key = (n: number) => JSON.stringify(String(n))

let out = `// generated by scripts/gen-dim-tables.ts — do not edit\n`
out += `export type Exp = ${exps.join(' | ')}\n\n`
out += `export type AddTable = {\n`
for (const a of exps) {
  const row = exps.map((b) => `${key(b)}: ${exps.includes(a + b) ? a + b : "'EXPONENT_OVERFLOW'"}`)
  out += `  ${key(a)}: { ${row.join('; ')} }\n`
}
out += `}\n\nexport type NegTable = { ${exps.map((a) => `${key(a)}: ${-a || 0}`).join('; ')} }\n`
writeFileSync(new URL('../src/core/dim-tables.gen.ts', import.meta.url), out)
console.log(`wrote dim tables for exponents ${-MAX}..${MAX}`)
