// generated by gen.mjs
export type AddTable = {
  "-4": { "-4": 'EXPONENT_OVERFLOW', "-3": 'EXPONENT_OVERFLOW', "-2": 'EXPONENT_OVERFLOW', "-1": 'EXPONENT_OVERFLOW', "0": -4, "1": -3, "2": -2, "3": -1, "4": 0 }
  "-3": { "-4": 'EXPONENT_OVERFLOW', "-3": 'EXPONENT_OVERFLOW', "-2": 'EXPONENT_OVERFLOW', "-1": -4, "0": -3, "1": -2, "2": -1, "3": 0, "4": 1 }
  "-2": { "-4": 'EXPONENT_OVERFLOW', "-3": 'EXPONENT_OVERFLOW', "-2": -4, "-1": -3, "0": -2, "1": -1, "2": 0, "3": 1, "4": 2 }
  "-1": { "-4": 'EXPONENT_OVERFLOW', "-3": -4, "-2": -3, "-1": -2, "0": -1, "1": 0, "2": 1, "3": 2, "4": 3 }
  "0": { "-4": -4, "-3": -3, "-2": -2, "-1": -1, "0": 0, "1": 1, "2": 2, "3": 3, "4": 4 }
  "1": { "-4": -3, "-3": -2, "-2": -1, "-1": 0, "0": 1, "1": 2, "2": 3, "3": 4, "4": 'EXPONENT_OVERFLOW' }
  "2": { "-4": -2, "-3": -1, "-2": 0, "-1": 1, "0": 2, "1": 3, "2": 4, "3": 'EXPONENT_OVERFLOW', "4": 'EXPONENT_OVERFLOW' }
  "3": { "-4": -1, "-3": 0, "-2": 1, "-1": 2, "0": 3, "1": 4, "2": 'EXPONENT_OVERFLOW', "3": 'EXPONENT_OVERFLOW', "4": 'EXPONENT_OVERFLOW' }
  "4": { "-4": 0, "-3": 1, "-2": 2, "-1": 3, "0": 4, "1": 'EXPONENT_OVERFLOW', "2": 'EXPONENT_OVERFLOW', "3": 'EXPONENT_OVERFLOW', "4": 'EXPONENT_OVERFLOW' }
}
export type NegTable = { "-4": 4, "-3": 3, "-2": 2, "-1": 1, "0": 0, "1": -1, "2": -2, "3": -3, "4": -4 }
