// generated by scripts/fetch-aws-prices.ts (pnpm gen:aws) — do not edit
// DynamoDB rates for us-east-1 (USD per usage unit), keyed by AWS usage-type name
// retrieved 2026-09-24 from:
//   https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/dynamodb/USD/current/dynamodb.json
// published 2026-09-11T12:44:22Z

export const dynamodbRetrieved = '2026-09-24'

export const dynamodbRates = {
  '1yr Read Capacity Unit Hrs Provisioned': { usd: 0.000025, rateCode: '4V475Q49DCKGXQZ2.YTVHEVGPBZ.6YS6EN2CT7' },
  '1yr Write Capacity Unit Hrs Provisioned': { usd: 0.000128, rateCode: 'R6PXMNYCEDGZ2EYN.YTVHEVGPBZ.6YS6EN2CT7' },
  '3yr Read Capacity Unit Hrs Provisioned': { usd: 0.000016, rateCode: '4V475Q49DCKGXQZ2.VG8YD49WWM.6YS6EN2CT7' },
  '3yr Write Capacity Unit Hrs Provisioned': { usd: 0.000081, rateCode: 'R6PXMNYCEDGZ2EYN.VG8YD49WWM.6YS6EN2CT7' },
  'Change Data Capture Units for AWS Glue Elastic Views': { usd: 1e-7, rateCode: '9HGBWJU6RANR5U7Y.JRTCKXETXF.6YS6EN2CT7' },
  'Change Data Capture Units for Kinesis Data Streams': { usd: 1e-7, rateCode: 'AKFBEQDKQJE2TU7K.JRTCKXETXF.6YS6EN2CT7' },
  'Data Storage Indexed - IA GB-Mo': { usd: 0.1, rateCode: 'DUA7FNC8NKEMZ7AA.JRTCKXETXF.6YS6EN2CT7' },
  'Data Storage Indexed Free Tier GB-Mo': { usd: 0, rateCode: 'F3E2EDSYC6ZNW7XP.JRTCKXETXF.G2A93NZ7DT' },
  'Data Storage Indexed GB-Mo': { usd: 0.25, rateCode: 'F3E2EDSYC6ZNW7XP.JRTCKXETXF.VYAP54KATQ' },
  'Export Data Size Incremental Export per GB': { usd: 0.1, rateCode: '3W5BGZNA3M3V96PD.JRTCKXETXF.6YS6EN2CT7' },
  'Export Data Size per GB': { usd: 0.1, rateCode: '3ADXMU9RYGKRUA9W.JRTCKXETXF.6YS6EN2CT7' },
  'Import Data Size': { usd: 0.15, rateCode: 'V54YY5S4S3DECX7A.JRTCKXETXF.6YS6EN2CT7' },
  'On-Demand Backup Storage GB-Month': { usd: 0.1, rateCode: 'EDC5UVDZNFN2S777.JRTCKXETXF.6YS6EN2CT7' },
  'PITR Backup Storage GB-Mo': { usd: 0.2, rateCode: 'TFXQN9PEG62G7A67.JRTCKXETXF.6YS6EN2CT7' },
  'PayPerRequest Read Request Units': { usd: 1.25e-7, rateCode: '4W4ZMC46EHE8XTTZ.JRTCKXETXF.6YS6EN2CT7' },
  'PayPerRequest Read Request Units IA': { usd: 1.55e-7, rateCode: 'YR9NFVSXEN3QWYDU.JRTCKXETXF.6YS6EN2CT7' },
  'PayPerRequest Replicated Write Request Units': { usd: 6.25e-7, rateCode: '3XWM5KJM296GT93W.JRTCKXETXF.6YS6EN2CT7' },
  'PayPerRequest Replicated Write Request Units IA': { usd: 7.8e-7, rateCode: '6NJM3K66JDV3SGNV.JRTCKXETXF.6YS6EN2CT7' },
  'PayPerRequest Write Request Units': { usd: 6.25e-7, rateCode: 'FGXVD96DKJMUASY3.JRTCKXETXF.6YS6EN2CT7' },
  'PayPerRequest Write Request Units IA': { usd: 7.8e-7, rateCode: 'MJVXP493BSJ5SKSQ.JRTCKXETXF.6YS6EN2CT7' },
  'Provisioned 1yr DDB-ReadUnits Upfront Fee': { usd: 0.3, rateCode: '4V475Q49DCKGXQZ2.YTVHEVGPBZ.2TG2D8R56U' },
  'Provisioned 1yr DDB-WriteUnits Upfront Fee': { usd: 1.5, rateCode: 'R6PXMNYCEDGZ2EYN.YTVHEVGPBZ.2TG2D8R56U' },
  'Provisioned 3yr DDB-ReadUnits Upfront Fee': { usd: 0.36, rateCode: '4V475Q49DCKGXQZ2.VG8YD49WWM.2TG2D8R56U' },
  'Provisioned 3yr DDB-WriteUnits Upfront Fee': { usd: 1.8, rateCode: 'R6PXMNYCEDGZ2EYN.VG8YD49WWM.2TG2D8R56U' },
  'Provisioned Read Units': { usd: 0.00013, rateCode: '4V475Q49DCKGXQZ2.JRTCKXETXF.E63J5HTPNN' },
  'Provisioned Read Units Free Tier': { usd: 0, rateCode: '4V475Q49DCKGXQZ2.JRTCKXETXF.HBHVWY47CM' },
  'Provisioned Read Units IA': { usd: 0.00016, rateCode: 'P7CSCRKZN8P5MR8C.JRTCKXETXF.6YS6EN2CT7' },
  'Provisioned Replicated Write Units': { usd: 0.00065, rateCode: 'QM7WV2JADZJDV45W.JRTCKXETXF.E63J5HTPNN' },
  'Provisioned Replicated Write Units IA': { usd: 0.00081, rateCode: 'MNQBR5JKF47TW9TE.JRTCKXETXF.6YS6EN2CT7' },
  'Provisioned Replicated Write UnitsFree Tier': { usd: 0, rateCode: 'QM7WV2JADZJDV45W.JRTCKXETXF.HBHVWY47CM' },
  'Provisioned Write Units': { usd: 0.00065, rateCode: 'R6PXMNYCEDGZ2EYN.JRTCKXETXF.E63J5HTPNN' },
  'Provisioned Write Units Free Tier': { usd: 0, rateCode: 'R6PXMNYCEDGZ2EYN.JRTCKXETXF.HBHVWY47CM' },
  'Provisioned Write Units IA': { usd: 0.00081, rateCode: '4PEFGG9BW5Z8Z57U.JRTCKXETXF.6YS6EN2CT7' },
  'Restore Data Size': { usd: 0.15, rateCode: 'Z79SYD7KXFPZZ9SF.JRTCKXETXF.6YS6EN2CT7' },
  'Streams Read Requests': { usd: 2e-7, rateCode: 'C7EPEWE3GFXXDMHR.JRTCKXETXF.AUKFMGQW43' },
  'Streams Read Requests Free Tier': { usd: 0, rateCode: 'C7EPEWE3GFXXDMHR.JRTCKXETXF.M9QGYPQ72M' },
} as const
