// Where catalog rates come from. Most rates are generated by scripts/fetch-aws-prices.ts into *.gen.ts files
// (DESIGN.md §5.4), each carrying its own retrieval date; inter-AZ transfer is still hand-curated.
import type { Source } from '../../pricing/dimension.ts'
import { doc } from '../../docs/registry.ts'
import { auroraRetrieved } from './aurora.gen.ts'
import { dynamodbRetrieved } from './dynamodb.gen.ts'
import { ec2SpecsRetrieved } from './ec2-specs.gen.ts'
import { ec2Retrieved } from './ec2.gen.ts'
import { s3Retrieved } from './s3.gen.ts'

/** date the hand-curated rates were verified */
export const RETRIEVED = '2026-09-24'

doc({
  name: 'RETRIEVED',
  kind: 'const',
  module: 'pricesim/aws',
  summary: "Date the catalog's hand-curated rates were last verified: '2026-09-24'.",
  guidance:
    '- Covers the rates written into the catalog modules (transfer, S3 Express, ELB, EBS, NAT gateway, internet egress, inter-region, PrivateLink, Direct Connect). Generated rates (EC2, S3 Standard, DynamoDB, Aurora) carry their own date in `SOURCES`.',
  seeAlso: ['SOURCES'],
  guide: 'catalog',
})

const src = (url: string, retrieved: string, note?: string): Source => ({ url, retrieved, ...(note ? { note } : {}) })

export const SOURCES = {
  ec2: src(
    'https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/ec2-ondemand-without-sec-sel/US%20East%20(N.%20Virginia)/Linux/index.json',
    ec2Retrieved,
    `baseline network, EBS and instance store from the EC2 instance-type docs (retrieved ${ec2SpecsRetrieved})`,
  ),
  s3: src('https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/s3/USD/current/s3.json', s3Retrieved),
  dynamodb: src(
    'https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/dynamodb/USD/current/dynamodb.json',
    dynamodbRetrieved,
  ),
  rds: src(
    'https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonRDS/current/us-east-1/index.csv',
    auroraRetrieved,
  ),
  aurora: src(
    'https://aws.amazon.com/rds/aurora/pricing/',
    auroraRetrieved,
    'Aurora Standard storage and I/O; rates from the RDS bulk price list (aurora.gen.ts)',
  ),
  transfer: src('https://aws.amazon.com/ec2/pricing/on-demand/#Data_Transfer_within_the_same_AWS_Region', RETRIEVED),
  s3Express: src(
    'https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonS3/current/us-east-1/index.csv',
    RETRIEVED,
    'usage types *-XZ-*; cross-checked against meteredUnitMaps/s3. Per-GB charges apply to all bytes since 2025-04-10',
  ),
  elb: src('https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AWSELB/current/us-east-1/index.csv', RETRIEVED),
  ebs: src(
    'https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/ebs.json',
    RETRIEVED,
    'US East (N. Virginia): Storage General Purpose gp3 GB Mo, Provisioned EBS IOPS gp3 Volumes per IOPS Mo, Provisioned Throughput gp3 per GiBps mo; free 3,000 IOPS and 125 MiB/s from https://docs.aws.amazon.com/ebs/latest/userguide/general-purpose.html',
  ),
  natGateway: src('https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/natgateway.json', RETRIEVED),
  internetEgress: src(
    'https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AWSDataTransfer/current/us-east-1/index.csv',
    RETRIEVED,
    'DataTransfer-Out-Bytes, US East (N. Virginia) -> External; 100 GB/month free tier from https://aws.amazon.com/s3/pricing/',
  ),
  interRegion: src(
    'https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AWSDataTransfer/current/us-east-1/index.csv',
    RETRIEVED,
    'Transfer Type InterRegion Outbound from us-east-1 (USE1-<dest>-AWS-Out-Bytes), publication 2026-09-16; cross-checked against meteredUnitMaps/datatransfer/USD/current/datatransfer.json',
  ),
  sameRegionPublic: src(
    'https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AWSDataTransfer/current/us-east-1/index.csv',
    RETRIEVED,
    'DataTransfer-Regional-Bytes ("in/out/between EC2 AZs or using elastic IPs or ELB"); both directions billed per https://docs.aws.amazon.com/cur/latest/userguide/cur-data-transfers-charges.html',
  ),
  privateLink: src(
    'https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonVPC/current/us-east-1/index.csv',
    RETRIEVED,
    'USE1-VpcEndpoint-Hours and tiered USE1-VpcEndpoint-Bytes; cross-checked against meteredUnitMaps/vpc/USD/current/vpc.json and https://aws.amazon.com/privatelink/pricing/',
  ),
  directConnect: src(
    'https://aws.amazon.com/directconnect/pricing/',
    RETRIEVED,
    'dedicated and hosted port-hours; DTO "Contiguous United States" to US locations $0.02/GB; DTI $0.00/GB. Billing account per https://aws.amazon.com/directconnect/faqs/. Flat rate: AWSDirectConnect price list (us-east-1, publication 2026-09-17) and https://docs.aws.amazon.com/directconnect/latest/PricingGuide/pricing-flat-rate.html',
  ),
} as const

doc({
  name: 'SOURCES',
  kind: 'catalog',
  module: 'pricesim/aws',
  summary: 'Where each catalog rate came from: a `{ url, retrieved, note? }` per AWS service.',
  signature: 'SOURCES: Record<string, { url: string; retrieved: string; note?: string }>',
  guidance: `
- Keys: \`ec2\`, \`s3\`, \`dynamodb\`, \`rds\`, \`aurora\`, \`transfer\`, \`s3Express\`, \`elb\`, \`ebs\`, \`natGateway\`, \`internetEgress\`, \`interRegion\`, \`sameRegionPublic\`, \`privateLink\`, \`directConnect\`.
- Every catalog billing dimension carries one as its \`source\`, and results show it per dimension (\`DimensionCost.source\`). All current dates are 2026-09-24.
- Pass one as \`source\` when you define your own dimension from the same price list.`,
  examples: [
    `import { SOURCES } from 'pricesim/aws'

console.log(SOURCES.ec2.url, SOURCES.ec2.retrieved)`,
  ],
  seeAlso: ['RETRIEVED', 'dimension'],
  guide: 'catalog',
})
