// Generates the exponent lookup tables and a synthetic EC2-sized catalog.
import { writeFileSync } from 'node:fs'

const exps = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
let t = '// generated by gen.mjs\n'
t += `export type AddTable = {\n`
for (const a of exps) {
  t += `  ${JSON.stringify(String(a))}: {`
  t += exps.map((b) => {
    const s = a + b
    return ` ${JSON.stringify(String(b))}: ${exps.includes(s) ? s : "'EXPONENT_OVERFLOW'"}`
  }).join(',')
  t += ` }\n`
}
t += `}\nexport type NegTable = {${exps.map((a) => ` ${JSON.stringify(String(a))}: ${-a || 0}`).join(',')} }\n`
writeFileSync('src/exp-table.ts', t)

// ~900 instance types, shaped like the real generated catalog would be
const families = ['m7g', 'm7i', 'm6g', 'm6i', 'c7g', 'c7i', 'c6g', 'c6i', 'r7g', 'r7i', 'r6g', 'r6i', 'i4g', 'i4i', 'im4gn', 'is4gen', 'x2gd', 'z1d', 't4g', 't3']
const sizes = [['medium', 1], ['large', 2], ['xlarge', 4], ['2xlarge', 8], ['4xlarge', 16], ['8xlarge', 32], ['12xlarge', 48], ['16xlarge', 64], ['24xlarge', 96], ['metal', 128]]
let c = `// generated by gen.mjs\nimport { q, u, instance } from '#core'\n\nexport const ec2 = {\n`
let n = 0
for (let rep = 0; rep < 5; rep++) {
  for (const f of families) {
    for (const [s, vcpu] of sizes) {
      const id = `${f}${rep ? '-v' + rep : ''}.${s}`
      c += `  '${id}': instance('${id}', { cpu: q(${vcpu * 1000}, u.millicore), memory: q(${vcpu * 4096}, u.MB), network: q(${(vcpu * 0.39).toFixed(2)}, u.Gbps), ebsBandwidth: q(${vcpu * 78}, u.MB.div(u.s)), ebsIops: q(${vcpu * 2500}, u.op.div(u.s)), price: q(${(vcpu * 0.0408).toFixed(4)}, u.USD.div(u.hour)) }),\n`
      n++
    }
  }
}
c += `} as const\n`
writeFileSync('src/catalog.gen.ts', c)
console.log('instances:', n)
